SELECT 
TO_CHAR(OS.SALES_DATE,'YYYY') YEAR, 
TO_NUMBER(TO_CHAR(OS.SALES_DATE,'MM')) MONTH, 
US.GENDER,
COUNT(DISTINCT US.USER_ID) USERS
FROM
ONLINE_SALE OS
LEFT OUTER JOIN USER_INFO US
ON OS.USER_ID = US.USER_ID
WHERE US.GENDER IS NOT NULL
GROUP BY
TO_CHAR(SALES_DATE,'YYYY'), 
TO_NUMBER(TO_CHAR(SALES_DATE,'MM')), 
US.GENDER
ORDER BY YEAR,MONTH,GENDER

