SELECT CAR_ID,CAR_TYPE,(DAILY_FEE * (1-(0.01*DISCOUNT_RATE)) * 30) FEE
FROM 
    (
        SELECT 
            A.CAR_ID, 
            A.DAILY_FEE,
            A.CAR_TYPE,
            B.DISCOUNT_RATE
        FROM 
            CAR_RENTAL_COMPANY_CAR A
        JOIN 
            CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON B.CAR_TYPE=A.CAR_TYPE
    WHERE B.DURATION_TYPE = '30일 이상' 
    AND B.CAR_TYPE IN('세단','SUV')
    )
    
WHERE CAR_ID 
NOT IN(
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE 
        TO_CHAR(START_DATE,'YYYYMMDD') <= '20221130'
    AND
        TO_CHAR(END_DATE,'YYYYMMDD') >= '20221101'
)

AND
    (DAILY_FEE * (1-(0.01*DISCOUNT_RATE)) * 30) >= 500000 AND
    (DAILY_FEE * (1-(0.01*DISCOUNT_RATE)) * 30) < 2000000

ORDER BY 
    FEE DESC, CAR_TYPE ASC, CAR_ID DESC
