SELECT TO_NUMBER(TO_CHAR(R.START_DATE,'MM')) AS MONTH, R.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
WHERE R.CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    WHERE TO_CHAR(R.START_DATE,'YYYY-MM') BETWEEN '2022-08'AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
AND TO_CHAR(R.START_DATE,'YYYY-MM') BETWEEN '2022-08'AND '2022-10'
GROUP BY TO_NUMBER(TO_CHAR(R.START_DATE,'MM')), R.CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH ASC, R.CAR_ID DESC;
