SELECT A.HOUR, COUNT(B.TIME) COUNT
FROM 
(SELECT LEVEL-1 AS HOUR 
FROM DUAL
CONNECT BY level <25
order by HOUR) A
LEFT OUTER JOIN (
SELECT TO_CHAR(ANIMAL_OUTS.DATETIME,'hh24') TIME 
FROM ANIMAL_OUTS
) B
ON A.HOUR = B. TIME
GROUP BY A.HOUR
ORDER BY A.HOUR;
    
