SELECT FLAVOR
FROM
(SELECT A.FLAVOR
FROM FIRST_HALF A
LEFT OUTER JOIN
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
    FROM 
        JULY 
    GROUP BY 
        FLAVOR
) B
ON A.FLAVOR = B.FLAVOR
ORDER BY (TOTAL+A.TOTAL_ORDER) DESC)
WHERE ROWNUM <= 3

-- -- 코드를 입력하세요
-- SELECT
--      A.FLAVOR    
-- FROM FIRST_HALF A,
-- (
--     SELECT 
--          FLAVOR
--         ,SUM(TOTAL_ORDER) AS SUM_ORDER
--     FROM JULY
--     GROUP BY FLAVOR
-- ) B
-- WHERE 1=1
-- AND A.FLAVOR = B.FLAVOR
-- ORDER BY (A.TOTAL_ORDER + B.SUM_ORDER) DESC
-- FETCH FIRST 3 ROWS ONLY

-- ;