SELECT NAME, DATETIME
FROM
(
SELECT AIN.NAME, AIN.DATETIME
FROM ANIMAL_INS AIN
LEFT OUTER JOIN 
    ANIMAL_OUTS AOU
    ON AIN.ANIMAL_ID = AOU.ANIMAL_ID
WHERE AOU.ANIMAL_TYPE IS NULL
order by datetime
    )
 WHERE   ROWNUM<4;
