SELECT B.HISTORY_ID, CAR.DAILY_FEE, B.DISCOUNT
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN 
(SELECT HISTORY_ID, HISTORY.CAR_ID CAR_ID,
CASE 
     WHEN (HISTORY.END_DATE - HISTORY.START_DATE) BETWEEN 0 AND 7 THEN 1
     WHEN (HISTORY.END_DATE - HISTORY.START_DATE) BETWEEN 7 AND 30 THEN 0.95
     WHEN (HISTORY.END_DATE - HISTORY.START_DATE) BETWEEN 30 AND 90 THEN 0.93
     ELSE 0.9 END DISCOUNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
WHERE HISTORY.CAR_ID IN 
(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR
WHERE CAR.CAR_TYPE ='트럭'
)
) B
ON 
CAR.CAR_ID = B.CAR_ID