SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
        CASE WHEN FREEZER_YN IS NULL THEN 'N' ELSE FREEZER_YN END 
        -- 만약에 FREEZER_YN이 NULL 이면 N 으로 바꾸고 나머지는 그대로
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기도%' -- 주소가 경기도인거만 고르기
ORDER BY WAREHOUSE_ID ASC -- 저장소 ID가 오름차순